name: Deploy Angular to VPS

on:
  push:
    branches:
      - main  # أي push على الفرع الرئيسي

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Angular
      run: npm run build --if-present

    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.NEW_VPS_HOST }}
        username: ${{ secrets.NEW_VPS_USER }}
        key: ${{ secrets.NEW_VPS_KEY }}
        port: 22
        source: "dist/store.ui/browser/*"
        target: "/var/www/eng-sy/"

    - name: Reload Nginx
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.NEW_VPS_KEY }}
        port: 22
        script: |
          nginx -t
          systemctl reload nginx
